#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
total = [2]
answer = 0
num = 0
a = 1
b = 2

while num < 4000000 :
    num = a + b
    a = b
    b = num
    #add to total amount if number is even
    if (num % 2) ==0:
        answer += num


#calculates the sum of all the numbers
print(answer+2)
